version: '3.8'

services:
  sistema_ticket_api:
    image: sistema_ticket
    container_name: sistema_ticket_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:ticketingdb
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - ticket_network

networks:
  ticket_network:
    driver: bridge
